name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: kea
          MYSQL_DATABASE: kea
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout kea-api
        uses: actions/checkout@v4

      - name: Checkout kea-docker
        uses: actions/checkout@v4
        with:
          repository: rannday/kea-docker
          path: kea-docker

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Build kea-custom Docker image
        run: docker build -t kea-custom:latest ./kea-docker

      - name: Run Kea container
        run: |
          docker run -d --name kea-int-test -p 8000:8000 kea-custom:latest
          echo "Waiting for Kea Control Agent..."
          until curl -s http://localhost:8000 | grep result; do sleep 1; done

      - name: Run unit tests
        run: go test ./...

      - name: Run integration tests
        run: go test -tags=integration ./...

      - name: Cleanup
        if: always()
        run: docker stop kea-int-test || true
